### ISSUE TITLE
nlp: find a way to grab an arbitrary website's privacy policy

### ISSUE THREAD

**Issue by jiaaaarui** [freed2003/gdpr-extension#9]
there's def some way to automate it but we could also have a fall back where we ask the user for it

**Comment by freed2003** [comment]
i think i can do this part

**Comment by jiaaaarui** [comment]
1. Grab the website's domain name
2. Make a search query with the domain name + privacy policy
3. Get the top result as the privacy policy page
4. use https://github.com/benandow/HtmlToPlaintext to process it
